version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongo_db:/data/db
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASS}
    networks:
      - app-network

  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    working_dir: /usr/app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    volumes:
      - .:/usr/app
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PASS}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo_db:
    driver: local

networks:
  app-network:
    driver: bridge